FROM ttl.sh/python-base:v0.1 as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . . 

RUN pip3 install --break-system-packages -r requirements.txt



# Expose the port that the application listens on.
EXPOSE 5000

# Run the application.
CMD python app/app.py
