name: python-pip-base

on:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Prepare Action
        uses: buildsafedev/multiarch-build--action/prepare-action@main
        with:
          oci_registry_username: ${{ secrets.DOCKER_USERNAME }}
          oci_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: holiodin01/python-pip-base
          ociBlock: python-dev
          tag: v0.1.0

  build:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, linux-arm64]  
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Build Action
        uses: buildsafedev/multiarch-build--action/build-action@main
        with:
          oci_registry_username: ${{ secrets.DOCKER_USERNAME }}
          oci_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          ociBlocks: python-dev
          directory: 'python-pip'

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Merge Action
        uses: buildsafedev/multiarch-build--action/merge-action@main
        with:
          oci_registry_username: ${{ secrets.DOCKER_USERNAME }}
          oci_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: holiodin01/python-pip-base
          ociBlock: python-dev
          tag: v0.1.0

  hermetic_builds:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Hermetic Build Action
        uses: buildsafedev/multiarch-build--action/hermetic-build@hermetic_builds
        with:
          oci_registry_username: ${{ secrets.DOCKER_USERNAME }}
          oci_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          directory: 'python-pip'
          image_name: holiodin01/python-pip-final
          tag: v0.1.0
          platform: linux/amd64
          base_image: holiodin01/python-pip-base:v0.1.0
          cosign_password : ${{ secrets.COSIGN_PASSWORD }}
          cosign_private_key : ${{ secrets.COSIGN_PRIVATE_KEY }}
          cosign_public_key : ${{ secrets.COSIGN_PUBLIC_KEY }}