name: rust-base
env:
  image_tag: v1
  REGISTRY: ttl.sh
  owner: buildsafedev
  runtime_image: rust-base-runtime
  dev_image: rust-base-dev
  final_image: rust-final
  final_arm64_image: rust-final-arm64
  final_amd64_image: rust-final-amd64

on:
  push:

jobs:
  prepare-rust-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Prepare Action
        uses: buildsafedev/multiarch-build--action/prepare-action@main
        with:
          oci_registry_username: ${{ env.owner}}
          oci_registry_password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ env.owner }}/${{ env.dev_image }}
          ociBlock: rust-dev
          tag: ${{ env.image_tag }}

  prepare-rust-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Prepare Action
        uses: buildsafedev/multiarch-build--action/prepare-action@main
        with:
          oci_registry_username: ${{ env.owner }}
          oci_registry_password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ env.owner }}/${{ env.runtime_image }}
          ociBlock: rust-runtime
          tag: ${{ env.image_tag }}

  build:
    needs: [prepare-rust-dev, prepare-rust-runtime]
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Action
        uses: buildsafedev/multiarch-build--action/build-action@main
        with:
          oci_registry_username: ${{ env.owner }}
          oci_registry_password: ${{ secrets.GITHUB_TOKEN }}
          ociBlocks: rust-dev rust-runtime
          directory: rust
          registry: ttl.sh

  final-img-build:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      amd64_digest: ${{ steps.build_amd64.outputs.digest }}
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download meta bake definition
        uses: actions/download-artifact@v4
        with:
          name: bake-meta-${{ format('rust-dev', 'rust-runtime') }}
          path: /tmp

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Verify digest files after download
        shell: bash
        run: |
          echo "Downloaded digest files:"
      - name: Build image amd64
        id: build_amd64
        working-directory: rust
        run: |
          docker buildx create --name mybuilder --use --driver docker-container
          docker buildx build \
          --no-cache \
          --tag ${{ env.REGISTRY }}/${{ env.owner }}/${{ env.final_amd64_image }}:${{ env.image_tag }} \
          --attest type=provenance,mode=min \
          --platform=linux/amd64 \
          --push \
          --output type=image \
          . 

          amd64_digest=$(docker manifest inspect ${{ env.REGISTRY }}/${{ env.owner }}/${{ env.final_amd64_image }}:${{ env.image_tag }} | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
          echo "digest=$amd64_digest" >> $GITHUB_OUTPUT

  scan_image:
    needs: final-img-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix development environment
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: ./rust/bsf/.#devShell


      - name: Is hermetic build
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{env.owner}}/${{ env.final_amd64_image }}:${{ env.image_tag }} --format "{{ json .Provenance.SLSA }}" > slsa.json
          cat slsa.json
          if grep -q "https://mobyproject.org/buildkit@v1#hermetic\": true" slsa.json; then
            echo "Hermetic build"
          else
            echo "Not a hermetic build"
          fi

      - name: Check for vulnerabilities
        run: grype ${{ env.REGISTRY }}/${{env.owner}}/${{ env.final_amd64_image }}:${{ env.image_tag }} --only-fixed --fail-on low
  

  sign_image:
    needs: scan_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
         cosign-release: 'v2.4.1'

      - name: Sign and push image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
           final_img_digest=$(docker manifest inspect ${{ env.REGISTRY }}/${{env.owner}}/${{ env.final_amd64_image }}:${{ env.image_tag }} | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
           cosign sign --yes ${{ env.REGISTRY }}/${{env.owner}}/${{ env.final_amd64_image }}@${final_img_digest}    

    